- defaults:
    link:
      relink: true

- clean: ['~']

- create:
     ~/obsidian:
      mode: 0755
 
- link:
    ~/obsidian/vault/.obsidian: obsidian
    ~/obsidian/vault/.obsidian.vimrc: obsidian.vimrc

- shell:
    - ['git submodule update --init --recursive', Install submodules]
